---
# Created by azhe on 2020-08-17 11:20

soft_name: kafka
install_path: "/opt"
soft_version: kafka_2.11-1.1.1

soft_pid_name: kafkaServer
parent_home: "{{install_path}}/{{soft_name}}"
soft_home: "{{parent_home}}/{{soft_version}}"

soft_profile: "/etc/profile.d/kafka_home.sh"
soft_file: "kafka_2.11-1.1.1.tgz"

soft_port: 9092
soft_conf: "{{ kafka_home }}/config/server{% if soft_port != 9092  %}-{{ soft_port }}{% endif %}.properties"

soft_datadir: "{{soft_home}}/data"
soft_datalogdir: "{{soft_home}}/logs"

#kafka工具
kafka_tools_name: kafka_tools_sasl
kafka_tools_path: "{{install_path}}/{{kafka_tools_name}}"
kafka_tools_profile: "/etc/profile.d/kafka_tools_home.sh"

#kafka权限

sasl_enable: 'false'
sasl_user: "admin"
sasl_password: "adminpwd"
sasl_mechanism: 'scram-sha256'
server_start_bash: kafka-server-start.sh
producer_bash: kafka-console-producer.sh
consumer_bash: kafka-console-consumer.sh
perf_test_bash: kafka-producer-perf-test.sh
producer_properties: producer.properties
consumer_properties: consumer.properties


installer_kafka: install