---
# author: wzq

- name: "{{installer_hive}} | 停止hive相关"
  shell: "ps -aux | grep {{item}} |grep -v grep| awk '{print $2}' | xargs kill -9"
  ignore_errors: True
  with_items:
    - 'hive-2.3.6'

- name: "{{installer_hive}} | 删除 {{parent_home}} 目录"
  file: path={{parent_home}} state=absent

- name: "{{installer_hive}} | 检查{{soft_profile}}环境变量是否存在"
  stat: path={{soft_profile}}
  register: soft_profile_result

- name: "{{installer_hive}} | 删除 {{soft_name}} 环境变量 {{soft_profile}}"
  file: path={{soft_profile}} state=absent
  when: soft_profile_result.stat.exists
