---
# Created by azhe on 2020-08-14 20:55

- name: configure | Create zookeeper data Directory.
  file: path={{ soft_datadir }} state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}

- name: configure | Set myid.
  template: dest={{ soft_datadir }}/myid src=myid.j2 owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}


- name: configure | Set zoo.cfg file.
  template:
    dest: "{{ soft_home }}/conf/zoo.cfg"
    mode: 0644
    src: zoo.cfg.j2
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: configure | start {{ soft_name }}.
  shell: "zkServer.sh start"
  become: false

- name: configure | Wait for Zookeeper port is OPEN.
  wait_for: "port={{ soft_port }} state=started"
