---
# Created by azhe on 2020-08-14 20:55


- name: "{{installer_zookeeper}} | 检查 {{ soft_name }} 安装目录 {{parent_home}} 是否存在"
  stat: path={{parent_home}}
  register: parent_home_result

- name: "{{installer_zookeeper}} | 如果目录不存在创建 {{parent_home}} 目录"
  file: path={{ parent_home }} state=directory
  when: not parent_home_result.stat.exists

- name: "{{installer_zookeeper}} | 检查 {{soft_home}} 目录是否存在"
  stat: path={{soft_home}}
  register: soft_home_result

- name: "{{installer_zookeeper}} | 解压{{soft_file}}"
  unarchive: src="{{basic_files_path}}/{{soft_name}}/{{soft_file}}" dest={{parent_home}}
  async: 0
  poll: 30
  when: not soft_home_result.stat.exists

- name: "{{installer_zookeeper}} | 检查{{soft_profile}}环境变量是否存在"
  stat: path={{soft_profile}}
  register: soft_profile_result

- name: "{{installer_zookeeper}} | 配置 {{soft_name}} 环境,环境变量写入{{soft_profile}}"
  template:
    src: soft_profile.sh.j2
    dest: '{{soft_profile}}'
    mode: 0644
  when: not soft_profile_result.stat.exists

- name: "{{installer_zookeeper}} | {{ soft_name }} version"
  command: '{{soft_home}}/bin/zkServer.sh -version'
  register: result
  changed_when: false
  ignore_errors: True

- debug: var=result.stderr_lines