---
# Created by azhe on 2020-08-17 16:33

- name: "{{installer_hadoop}} | 安装psmisc"
  yum:
     name: psmisc
     state: present

- name: "{{installer_hadoop}} | 创建 {{parent_home}} , {{hadoop_data_home}} 目录"
  file:
    path: "{{ item }}"
    state: directory
    owner: '{{ansible_user}}'
    group: '{{ansible_user}}'
  with_items:
   - "{{parent_home}}"
   - "{{hadoop_data_home}}"
   - "{{hadoop_yarn_logs_home}}"

- name: "{{installer_hadoop}} | 检查 {{ soft_name }} 安装目录 {{soft_home}} 是否存在"
  stat: path={{ soft_home }}
  register: parent_home_result

- name: "{{installer_hadoop}} | 安装{{soft_name}}"
  unarchive:
    src: "{{basic_files_path}}/{{soft_name}}/{{soft_version}}/{{soft_version}}.tar.gz"
    dest: "{{parent_home}}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  async: 0
  poll: 30
  when: not parent_home_result.stat.exists

- name: "{{installer_hadoop}} | 检查{{soft_profile}}环境变量是否存在"
  stat: path={{soft_profile}}
  register: soft_profile_result

- name: "{{installer_hadoop}} | 配置 {{soft_name}} 环境,环境变量写入{{soft_profile}}"
  template:
    src: soft_profile.sh.j2
    dest: '{{soft_profile}}'
    mode: 0644
  when: not soft_profile_result.stat.exists