---
# Created by azhe on 2020-09-15 11:34

- name: "{{installer_hadoop}} | 启动 namenode "
  shell: hadoop-daemon.sh start namenode
  when: inventory_hostname in ( groups['hadoop_dfs_namenode'] )
  become: false

- name: "{{installer_hadoop}} | 启动 datanode "
  shell: hadoop-daemon.sh start datanode
  when: inventory_hostname in ( groups['hadoop_dfs_datanode'] )
  become: false

- name: "{{installer_hadoop}} | 启动 journalnode "
  shell: hadoop-daemon.sh start journalnode
  when: inventory_hostname in ( groups['hadoop_dfs_journalnode'] )
  become: false

- name: "{{installer_hadoop}} | 启动 zkfc "
  shell: hadoop-daemon.sh start zkfc
  when: inventory_hostname in ( groups['hadoop_dfs_namenode'] )
  become: false