global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:{{ prometheus_port }}']
        labels:
          instance: prometheus

  - job_name: linux
    static_configs:
{% for host in groups['all'] %}
      - targets: ['{{hostvars[host].ansible_ssh_host }}:{{ node_exporter_port }}']
{% endfor %}

  - job_name: kafka
    static_configs:
{% for host in groups['kafka_exporter'] %}
      - targets: ['{{ ansible_ssh_host }}:{{ kafka_exporter_port }}']
        labels:
          instance: kafka@{{ ansible_ssh_host }}
{% endfor %}