---
# Created by azhe on 2020-03-13 19:07

- name: "{{installer_java}} | 检查 {{ soft_name }} 安装目录 {{parent_home}} 是否存在"
  stat: path={{ parent_home }}
  register: parent_home_result

- name: "{{installer_java}} | 如果目录不存在创建 {{parent_home}} 目录"
  file: path={{ parent_home }} state=directory
  when: not parent_home_result.stat.exists

- name: "{{installer_java}} | 检查 {{soft_home}} 目录是否存在"
  stat: path={{soft_home}}
  register: soft_home_result

#- name: 检查 {{soft_file}} 文件是否存在
#  become: false
#  connection: local
#  shell: "ls roles/java/files/{{soft_file}}"
#  register: java_file_result
#  ignore_errors: True

- name: "{{installer_java}} | 安装{{soft_name}}"
  unarchive: src="{{basic_files_path}}/{{soft_name}}/{{soft_version}}/{{soft_version}}.tar.gz" dest={{parent_home}}
  async: 0
  poll: 30
  when: not soft_home_result.stat.exists

- name: "{{installer_java}} | 检查{{soft_profile}}环境变量是否存在"
  stat: path={{soft_profile}}
  register: soft_profile_result

- name: "{{installer_java}} | 配置 {{soft_name}} 环境,环境变量写入{{soft_profile}}"
  template:
    src: soft_profile.sh.j2
    dest: '{{soft_profile}}'
    mode: 0644
  when: not soft_profile_result.stat.exists

- name: "{{installer_java}} | {{ soft_name }} version"
  command: '{{soft_home}}/bin/java -version'
  register: result
  changed_when: false
  ignore_errors: True

- debug: var=result.stderr_lines