---
# Created by azhe on 2020-08-17 11:20


- name: "{{installer_kafka}} | Set config file."
  template:
    dest: "{{ soft_home }}/config/server.properties"
    mode: 0644
    src: server.properties.j2
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: "{{installer_kafka}} | 添加jmx端口 "
  lineinfile:
    dest: '{{soft_home}}/bin/{{server_start_bash}}'
    insertafter: "# limitations"
    line: "export JMX_PORT=9999"
    state: present

- name: "{{installer_kafka}} | Create {{soft_name}} data Directory."
  file: path={{ item }} state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}
  with_items:
   - "{{ soft_datadir }}"
   - "{{ soft_datalogdir }}"
